services:
  guacamole:
    image: jwetzell/guacamole:latest
    container_name: guacamole
    volumes:
      - "/var/lib/srv/$USER/docker/jwetzell/guacamole/latest/rootfs/data/db/postgres:/config"
    ports:
      - 8080:8080
   environment:
      - TZ=America/New_York
volumes:
  postgres:
    driver: local

networks:
  guacamole:
